question_data = [{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "Peter Molyneux was the founder of Bullfrog Productions.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "The name of the main character of the video game &quot;The Legend of Zelda&quot;, is Zelda.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Clefairy was intended to be Ash&#039;s starting Pok&eacute;mon in the pilot episode of the cartoon.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "A slug&rsquo;s blood is green.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The Cold War ended with Joseph Stalin&#039;s death.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "A group of islands is called an &#039;archipelago&#039;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The Tiananmen Square protests of 1989 were held in Hong Kong.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "The Mann Co. Store from Team Fortress 2 has the slogan &quot;We hire mercenaries and get in fights&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "Matt Damon played an astronaut stranded on an extraterrestrial planet in both of the movies Interstellar and The Martian.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
                  "question": "The book 1984 was published in 1949.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "There are 6 legendary cards in &quot;Clash Royale&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
                  "question": "The &#039;Squaring the Circle&#039; problem is solvable.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "Luigi is taller than Mario?", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "The game &quot;Battlefield 1&quot; takes place during World War I.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "Pac-Man was invented by the designer Toru Iwatani while he was eating pizza.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "In Kingdom Hearts the Paopu fruit is said to intertwine the destinies for two people forever.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "A bear does NOT defecate during hibernation. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Gadgets", "type": "boolean", "difficulty": "easy",
                  "question": "The communication protocol NFC stands for Near-Field Control.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Bill Cipher in the show &quot;Gravity Falls&quot; is the good guy.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "Ottawa is the capital of Canada.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Politics", "type": "boolean", "difficulty": "easy",
                  "question": "The 2016 United States Presidential Election is the first time Hillary Clinton has run for President.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "The PlayStation was originally a joint project between Sega and Sony that was a Sega Genesis with a disc drive.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "The 2005 video game &quot;Call of Duty 2: Big Red One&quot; is not available on PC.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after filming.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "Toronto is the capital city of the North American country of Canada.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "St. Louis is the capital of the US State Missouri.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "&quot;HTML&quot; stands for Hypertext Markup Language.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "In the game &quot;Subnautica&quot;, a &quot;Spadefish&quot; will attack you.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
                  "difficulty": "easy",
                  "question": "The name of the attack &quot;Kamehameha&quot; in Dragon Ball Z was named after a famous king of Hawaii.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Sports", "type": "boolean", "difficulty": "easy",
                  "question": "Roger Federer is a famous soccer player.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "In &quot;Undertale&quot;, the main character of the game is Sans.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "In World War ll, Great Britian used inflatable tanks on the ports of Great Britain to divert Hitler away from Normandy\/D-day landing.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "Adolf Hitler was tried at the Nuremberg trials.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
                  "question": "In &quot;Star Trek&quot;, Klingons are aliens.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Art", "type": "boolean", "difficulty": "easy",
                  "question": "Leonardo da Vinci was not the creator of the Mona Lisa.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
                  "question": "In &quot;Doctor Who&quot;, the Doctor gets his TARDIS by stealing it.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "Hungary is the only country in the world beginning with H.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In the &quot;To Love-Ru&quot; series, Golden Darkness is sent to kill Lala Deviluke.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
                  "question": "The sum of any two odd integers is odd.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside swimming pools and drinking water.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "New Haven is the capital city of the state of Connecticut in the United States.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                  "question": "The 2011 movie &quot;The Adventures of Tintin&quot; was directed by Steven Spielberg.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
                  "question": "An equilateral triangle always has every angle measuring 60&deg;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "A pasodoble is a type of Italian pasta sauce.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
                  "question": "&quot;The Simpsons&quot; family is named after creator Matt Groening&#039;s real family.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "In Until Dawn, both characters Sam and Mike cannot be killed under any means until the final chapter of the game.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "Each piece in Tetris is called a tetris.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "The mitochondria is the powerhouse of the cell.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
